- type: entity
  parent: BaseItem
  id: BaseArtifact
  name: артефакт
  suffix: Stalker
  abstract: true
  components:
    - type: PsyonicsAbsorbable
    - type: STWeight
      self: 5
    - type: PointLightDisableOnEquip
    - type: ZoneArtifactDetectorTarget
      detectable: true
      detectedLevel: 1
    - type: SpawnAnomalyZoneArtifact
    - type: DetectorZoneArtifact
    - type: Item
      size: Normal
      shape:
      - 0,0,1,1
    - type: Sprite
      sprite: _Stalker/Objects/artifacts.rsi
      state: soul
    - type: Clothing
      quickEquip: true
      slots:
        - ARTIFACT
    - type: Tag
      tags:
      - Khabar
      - STArtifact
    - type: Material
    - type: RepositoryItem
      categoryName: repository-artifact-category
    - type: Craftable
    - type: Currency
      price:
        Roubles: 1
        Dollar: 1
        Hryvnias: 0 # EN

- type: entity
  parent: BaseArtifact
  id: BaseArtifactStorage
  abstract: true
  components:
    - type: Storage
      maxItemSize: Huge
      grid:
        - 0,0,3,3
    - type: UserInterface
      interfaces:
        enum.StorageUiKey.Key:
          type: StorageBoundUserInterface
    - type: ContainerContainer
      containers:
        storagebase: !type:Container
          ents: []
